### ISSUE TITLE
can we use this sheet?

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/tensor-something#5]
just open this article from NYT and find that they shared some ingredients csv.
can we use it? 
https://open.blogs.nytimes.com/2016/04/27/structured-ingredients-data-tagging/
https://raw.githubusercontent.com/NYTimes/ingredient-phrase-tagger/master/nyt-ingredients-snapshot-2015.csv

**Comment by philippeTUESIGELEC** [comment]
For the recommender system ? Not really. We need data coming directly from Groceristar users.

**Comment by atherdon** [comment]
no, i mean for additional source of ingredients. for sure, 5k of ingredients is enough for current project stage, but maybe we can grab some additional information...

**Comment by philippeTUESIGELEC** [comment]
Okay, for additional source of ingredients. I'll work on it then. I'll come back to you when I've finished. I'am also creating a ticket.

**Comment by atherdon** [comment]
good - thank you! should i close this task?
