### ISSUE TITLE
Am i find a gem?

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/tensor-something#7]
Hi @philippeTUESIGELEC, hope things going well on your side!
Please check this dataset: https://www.kaggle.com/jboysen/global-food-prices/data
i compared my country prices and

i think if we grab just a US prices with basic food names - it can be another good feature for Groceristar.
Tell me what do you think

**Comment by philippeTUESIGELEC** [comment]
Hi Arthur,
I'll extract US prices and basic food names on this dataset if you're interested in those data.
I'll come back to you when its done.

Philippe.

**Comment by atherdon** [comment]
Perfect! thanks

**Comment by philippeTUESIGELEC** [comment]
Question : 
You just want rows that has USD on currency and foodnames ?

Philippe.

**Comment by atherdon** [comment]
i think yeah, for now i assume it will be enough. or what do you think? maybe you have a better idea than just grab that data from file...

**Comment by philippeTUESIGELEC** [comment]
Are you sure you want to use those prices ? These are from the global food market. I think those prices are different from what we find in the supermarket in general. I guess you wanted to provide prices for ingredients but I think those data don't match with the real price people pay. 
Do you still want to work with those prices ? 

Philippe.

**Comment by atherdon** [comment]
i think that avg prices will work ok for now, so yeah i think we'll use it - and if users will ok on that - we'll keep it

**Comment by philippeTUESIGELEC** [comment]
Hi Arthur,

The task is done, you'll find the result in  the following folder : 
"US food and price 27 04 2018"

That's not a lot of food, only 28 for food that has USD as a currency. The prices are the mean prices for all the year foods has been measured as you asked.

Tell me if you need anything else.

Philippe.

**Comment by atherdon** [comment]
got it - thank you! will check it out
